const data = {
  customer: {
    collection: [
      {
        alamat: "JALAN YOS SUDARSO KOMPLEK BRAYAN PERMAI NO 5",
        email: "hasankho289@gmail.com",
        kota: "MEDAN",
        kurir:
          "Wahana (Biaya Kirim Akan di Info Setelah Barang Sampai di Jakarta)",
        nama: "Hasan Gunawan",
        telp: "0851-0035-5620",
        zip: "20116",
        sales: null,
      },
      {
        alamat: "Jalan Siwalankerto Timur V No. 151A",
        email: "dwilitaaprilin.98@gmail.com",
        kota: "Surabaya Town",
        kurir:
          "Sentral Cargo (Biaya Kirim Akan di Info Setelah Barang Sampai di Jakarta)",
        nama: "Dwilita Aprilin",
        telp: "0812-3261-3251",
        zip: "60236",
        sales: null,
      },
      {
        alamat:
          "Jalan  hasan saad no 14 Toko bina, kelurahan condong ,kecamatan singkawang tengah kode pos 79111",
        email: "salvianfebrianto23@gmail.com",
        kota: "Kota singkawang",
        kurir: "JABODETABEK",
        nama: "Kon con Min",
        telp: "0813-4545-1615",
        zip: "79111",
        sales: null,
      },
      {
        alamat: "Jl. Rawa bahagia raya no. 43",
        email: "mirakur970@gmail.com",
        kota: "Jakarta Barat",
        kurir: "JABODETABEK",
        nama: "Deni Kurniawan",
        telp: "0812-8727-9397",
        zip: "11450",
        sales: null,
      },
      {
        alamat: "Jalan Puma 8 no 39, Jayamukti, Cikarang Pusat",
        email: "business.seduhpertama@gmail.com",
        kota: "Cikarang Pusat",
        kurir: "JABODETABEK",
        nama: "Alvi Faidaturrosyida",
        telp: "6282244622363",
        zip: "17531",
        sales: null,
      },
      {
        alamat: "Margosari Rt 04 Rw 02 Ds. Kuwaron Kec. Gubug",
        email: "scootyrick@gmail.com",
        kota: "Grobogan",
        kurir:
          "Wahana (Biaya Kirim Akan di Info Setelah Barang Sampai di Jakarta)",
        nama: "ricky rizaldi",
        telp: "089669310177",
        zip: "58164",
        sales: null,
      },
      {
        alamat:
          "Jl Raya Jatibening 2 no 20 rt 02/04 Jatibening baru pondok gede bekasi 17412",
        email: "rillatheromusha@gmail.com",
        kota: "Bekasi",
        kurir: "JABODETABEK",
        nama: "amarilla mulyanto",
        telp: "085921955365WA:087788966643",
        zip: "17412",
        sales: "kris",
      },
      {
        alamat: "Jl. Tanah merah 2/46A",
        email: "ivan.topi.golf@gmail.com",
        kota: "Surabaya",
        kurir: "JABODETABEK",
        nama: "Ivan Ivan",
        telp: "0898-3425-489",
        zip: "60129",
        sales: null,
      },
      {
        alamat: "CBD Gading Serpong Barat",
        email: "ria.y.toelle@gmail.com",
        kota: "Tangerang",
        kurir: "JABODETABEK",
        nama: "Ria Toelle",
        telp: "0819-0438-0016",
        zip: "15810",
        sales: null,
      },
    ],
  },
  finance: {
    collection: [
      {
        income: 6451400,
        expense: null,
        shipping: null,
        profit: 6451400,
        percentage: null,
      },
      {
        income: 1000152,
        expense: null,
        shipping: null,
        profit: 1000152,
        percentage: null,
      },
      {
        income: 2493900,
        expense: null,
        shipping: null,
        profit: 2493900,
        percentage: null,
      },
      {
        income: 10642500,
        expense: null,
        shipping: null,
        profit: 10642500,
        percentage: null,
      },
      {
        income: 1080000,
        expense: null,
        shipping: null,
        profit: 1080000,
        percentage: null,
      },
      {
        income: 1140000,
        expense: null,
        shipping: null,
        profit: 1140000,
        percentage: null,
      },
      {
        income: 1000658,
        expense: null,
        shipping: null,
        profit: 1000658,
        percentage: null,
      },
      {
        income: 2020000,
        expense: null,
        shipping: null,
        profit: 2020000,
        percentage: null,
      },
      {
        income: 1008000,
        expense: 255300,
        shipping: null,
        profit: 752700,
        percentage: 394.82961222091654,
      },
    ],
  },
  idOrders: {
    collection: [
      {
        id_so: 6602,
        warning: true,
        paymentDate: "3/9/2021 10.51.58",
        notes: [
          {
            sales: "wahyu",
            note: "sda",
            date: "Invalid Date",
          },
        ],
      },
      {
        id_so: 7302,
        warning: true,
        paymentDate: "22/9/2021 22.46.43",
        notes: null,
      },
      {
        id_so: 7545,
        warning: true,
        paymentDate: "29/9/2021 09.32.31",
        notes: null,
      },
      {
        id_so: 7719,
        warning: true,
        paymentDate: "2/10/2021 12.49.28",
        notes: null,
      },
      {
        id_so: 7727,
        warning: true,
        paymentDate: "4/10/2021 09.08.03",
        notes: null,
      },
      {
        id_so: 7859,
        warning: true,
        paymentDate: "7/10/2021 11.17.57",
        notes: null,
      },
      {
        id_so: 7880,
        warning: true,
        paymentDate: "7/10/2021 18.28.18",
        notes: null,
      },
      {
        id_so: 7888,
        warning: true,
        paymentDate: "8/10/2021 01.24.02",
        notes: null,
      },
      {
        id_so: 7890,
        warning: true,
        paymentDate: "8/10/2021 08.15.43",
        notes: null,
      },
    ],
  },
  orders: {
    collection: [
      [
        {
          id_so: 6602,
          name: "Chenlu keran Produsen kuningan Mingjia triple bathtub dan shower kran tersembunyi dinding kamar mandi rumah",
          qty: 100,
          price: 64514,
          variant: "6437-1",
        },
      ],
      [
        {
          id_so: 7302,
          name: "2018 Baru Korea klip telinga tanpa tindik fashion sederhana telinga klip wanita segitiga anting-anting anting-anting grosir",
          qty: 30,
          price: 4919,
          variant: "7036-24",
        },
        {
          id_so: 7302,
          name: "2018 Baru Korea klip telinga tanpa tindik fashion sederhana telinga klip wanita segitiga anting-anting anting-anting grosir",
          qty: 30,
          price: 4919,
          variant: "7036-23",
        },
        {
          id_so: 7302,
          name: "2018 Baru Korea klip telinga tanpa tindik fashion sederhana telinga klip wanita segitiga anting-anting anting-anting grosir",
          qty: 30,
          price: 3891,
          variant: "7036-20",
        },
      ],
      [
        {
          id_so: 7545,
          name: "Sayuran penanaman lubang seedling tray kecambah bibit tray",
          qty: 600,
          price: 2771,
          variant: "7306-13",
        },
        {
          id_so: 7545,
          name: "Sayuran penanaman lubang seedling tray kecambah bibit tray",
          qty: 300,
          price: 2771,
          variant: "7306-6",
        },
      ],
      [
        {
          id_so: 7719,
          name: "casserole api terbuka dan tahan suhu tinggi sup casserole keramik sup rebus (MOQ 50 pcs)",
          qty: 30,
          price: 212850,
          variant: "7357-4",
        },
        {
          id_so: 7719,
          name: "casserole api terbuka dan tahan suhu tinggi sup casserole keramik sup rebus (MOQ 50 pcs)",
          qty: 20,
          price: 212850,
          variant: "7357-3",
        },
      ],
      [
        {
          id_so: 7727,
          name: "Eropa mug kreatif keramik pola marmer piala pernikahan tangan hadiah disesuaikan logo kantor gelas air",
          qty: 5,
          price: 36000,
          variant: "7426-14",
        },
        {
          id_so: 7727,
          name: "Eropa mug kreatif keramik pola marmer piala pernikahan tangan hadiah disesuaikan logo kantor gelas air",
          qty: 5,
          price: 36000,
          variant: "7426-13",
        },
        {
          id_so: 7727,
          name: "Eropa mug kreatif keramik pola marmer piala pernikahan tangan hadiah disesuaikan logo kantor gelas air",
          qty: 5,
          price: 36000,
          variant: "7426-10",
        },
      ],
      [
        {
          id_so: 7859,
          name: "Sepeda motor bensin fuel filter 90 derajat sudut kanan 60470101120",
          qty: 150,
          price: 7600,
          variant: "7605-1",
        },
      ],
      [
        {
          id_so: 7880,
          name: "Anak dasi busur sutra poliester acara permen warna tampan fashion bayi dasi hewan peliharaan grosir kustom",
          qty: 10,
          price: 2038,
          variant: "7544-17",
        },
        {
          id_so: 7880,
          name: "Anak dasi busur sutra poliester acara permen warna tampan fashion bayi dasi hewan peliharaan grosir kustom",
          qty: 10,
          price: 2038,
          variant: "7544-15",
        },
        {
          id_so: 7880,
          name: "Anak dasi busur sutra poliester acara permen warna tampan fashion bayi dasi hewan peliharaan grosir kustom",
          qty: 10,
          price: 2038,
          variant: "7544-14",
        },
      ],
      [
        {
          id_so: 7888,
          name: "golf cap pria bergerak lingkar kepala golf topi bernapas cepat kering deodoran mesh",
          qty: 3,
          price: 202000,
          variant: "7618-10",
        },
        {
          id_so: 7888,
          name: "golf cap pria bergerak lingkar kepala golf topi bernapas cepat kering deodoran mesh",
          qty: 4,
          price: 202000,
          variant: "7618-7",
        },
        {
          id_so: 7888,
          name: "golf cap pria bergerak lingkar kepala golf topi bernapas cepat kering deodoran mesh",
          qty: 3,
          price: 202000,
          variant: "7618-5",
        },
      ],
      [
        {
          id_so: 7890,
          name: "Pabrik grosir baking Alat combo 8 longgar bawah kue pan 6 Buah pizza baja karbon roti square ovenware",
          qty: 5,
          price: 17000,
          variant: "7634-12",
        },
        {
          id_so: 7890,
          name: "Pabrik grosir baking Alat combo 8 longgar bawah kue pan 6 Buah pizza baja karbon roti square ovenware",
          qty: 5,
          price: 30500,
          variant: "7634-11",
        },
        {
          id_so: 7890,
          name: "Pabrik grosir baking Alat combo 8 longgar bawah kue pan 6 Buah pizza baja karbon roti square ovenware",
          qty: 6,
          price: 16000,
          variant: "7634-10",
        },
      ],
    ],
  },
};

export default data;
